GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    content: "sample post",
    important: false
}


###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "sample post",
    "important": false
}

###
DELETE http://localhost:3001/api/persons/4

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Thunk Trampoline is the best DnD character ever",
  "important": false
}

###
GET http://localhost:3001/api/yes

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Clock",
  "number": "00-0000000"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Thunk Trampoline",
  "number": "12-3456789"
}

###
DELETE http://localhost:3001/api/persons/6719

###
GET http://localhost:3001/api/persons